#!/bin/sh

APPDIR=$0

if [ ! -e "$APPDIR" ]; then
	case $APPDIR in
		(*/*) exit 1;;
		(*) APPDIR=$(command -v -- "$APPDIR") || exit;;
	esac
fi

APPDIR=$(
	cd -P -- "$(dirname -- "$APPDIR")" && pwd -P
) || exit

if [ -f ~/.profile ]; then
	sed -e '/^export RP_CMDRC_DIR/d' ~/.profile > ~/.profile.tmp
fi

echo export RP_CMDRC_DIR=$APPDIR >> ~/.profile.tmp

mv -f ~/.profile.tmp ~/.profile
rm -f ~/.profile.tmp

exec $APPDIR/rprccmd.bin "$@"
